In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [3]:
file_path = 'shakespeare.txt'
text = open(file_path, 'r').read()
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [4]:
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

In [5]:
char_to_ind = {u:i for i, u in enumerate(vocab)}
char_to_ind

ind_to_char = np.array(vocab)
ind_to_char

encoded_text =np.array([char_to_ind[c] for c in text ])
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [6]:
sample = text[:20]
sample

'\n                   '

In [7]:
encoded_text[:20]
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [8]:
print(text[:5000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [9]:
line = 'From fairest creatures we desire increase'
len(line)

41

In [10]:
part_stanza = """From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But as the riper should by time decease,"""

len(part_stanza)

127

In [11]:
seq_len = 120
total_num_seq = len(text)//(seq_len+1)
total_num_seq

45005

In [12]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
for i in char_dataset.take(500):
    print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [13]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [14]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [15]:
dataset = sequences.map(create_seq_targets)

In [16]:
for input_txt, target_txt in dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print(''.join(ind_to_char[target_txt.numpy()]))


[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [17]:
batch_size = 128
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [18]:
vocab_size = len(vocab)
embed_dim = 64
rnn_neurons = 1026

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Dropout, GRU

In [20]:
from tensorflow.keras.losses import sparse_categorical_crossentropy
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2

In [21]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)


In [22]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [23]:
model = create_model(
    vocab_size=vocab_size,
    embed_dim=embed_dim,
    rnn_neurons=rnn_neurons,
    batch_size=batch_size
)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape, "<=== (batch_size, sequence_length, vocab_size)")
    

(128, 120, 84) <=== (batch_size, sequence_length, vocab_size)


In [25]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[ 6.2966987e-04, -1.3033641e-03, -4.2580031e-03, ...,
          1.6880346e-03,  2.4642767e-03, -2.1369685e-03],
        [ 2.0285216e-03, -3.9936113e-03, -9.8586734e-03, ...,
          8.6681386e-03,  7.9042194e-03, -4.2659873e-03],
        [ 5.1922794e-03, -7.1015547e-04, -1.0900713e-02, ...,
          5.2549429e-03,  2.8789877e-03,  2.6697805e-03],
        ...,
        [ 2.9883517e-03,  6.7420019e-04, -9.1333473e-03, ...,
          2.7178924e-03,  6.0872100e-03, -2.0642884e-03],
        [-9.4996532e-04, -3.7981088e-05, -3.1851307e-03, ...,
          1.0065209e-02, -3.0597197e-03, -4.1713500e-03],
        [-2.8589750e-03,  8.6709234e-04, -3.7017086e-04, ...,
          1.6633193e-03, -1.2924829e-03, -5.4986859e-03]],

       [[ 2.3743741e-03,  3.3582894e-03,  5.2732192e-03, ...,
         -1.7567712e-04, -3.1484910e-03,  5.4837349e-03],
        [ 3.5843968e-03,  9.3168076e-03,  7.4945739e-03, ...,
         -4.3058950e-03,  2

In [26]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[38],
       [56],
       [59],
       [32],
       [67],
       [14],
       [17],
       [25],
       [28],
       [68],
       [76],
       [39],
       [47],
       [31],
       [64],
       [30],
       [ 7],
       [64],
       [16],
       [68],
       [14],
       [34],
       [32],
       [18],
       [ 9],
       [72],
       [27],
       [46],
       [47],
       [ 5],
       [21],
       [15],
       [27],
       [25],
       [77],
       [21],
       [39],
       [75],
       [42],
       [36],
       [75],
       [56],
       [18],
       [35],
       [40],
       [ 1],
       [73],
       [83],
       [27],
       [43],
       [21],
       [38],
       [78],
       [56],
       [64],
       [60],
       [33],
       [38],
       [77],
       [12],
       [21],
       [69],
       [40],
       [26],
       [10],
       [17],
       [ 1],
       [52],
       [11],
       [ 2],
       [46],
       [42],
       [73],
   

In [27]:
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()
sampled_indices

array([38, 56, 59, 32, 67, 14, 17, 25, 28, 68, 76, 39, 47, 31, 64, 30,  7,
       64, 16, 68, 14, 34, 32, 18,  9, 72, 27, 46, 47,  5, 21, 15, 27, 25,
       77, 21, 39, 75, 42, 36, 75, 56, 18, 35, 40,  1, 73, 83, 27, 43, 21,
       38, 78, 56, 64, 60, 33, 38, 77, 12, 21, 69, 40, 26, 10, 17,  1, 52,
       11,  2, 46, 42, 73,  7, 39,  8,  4, 69, 71, 80, 40, 15, 50, 74, 29,
       38, 64, 20, 12, 57, 41, 51, 17,  5, 52, 37, 67, 35, 65, 79,  1, 31,
       28,  3, 51, 11, 21, 46, 39, 77, 44,  0, 50, 21, 72, 52, 54, 79, 82,
       22])

In [28]:
print('Given the input seq: \n')
print("".join((ind_to_char[input_example_batch[0]])))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices]))

Given the input seq: 

ech you, peace!
    Or, if you'd ask, remember this before:
    The thing I have forsworn to grant may never
    Be held


Next Char Predictions: 

MadGl36?CmuNVFiE)i5m3IG7-qBUV':4B?v:NtQKta7JO r}BR:MwaieHMv1:nOA.6 [0!UQr)N,&npyO4YsDMi91bPZ6'[LlJjx FC"Z0:UNvS
Y:q[_x|;


In [29]:
epochs = 30

model.fit(dataset, epochs=epochs)

Epoch 1/30
351/351 [==============================] - 651s 2s/step - loss: 2.5994
Epoch 2/30
311/351 [=========================>....] - ETA: 1:19 - loss: 1.8136

KeyboardInterrupt: 